---
# general params
env_params:
  # high level params
  domain_name: hopper
  task_name: stand

  # image params
  height: 224
  width: 224

  # basic env params
  from_pixels: true
  visualize_reward: false

agent_params:
  # agent and extractor
  algo: DDPG
  model_type: CnnPolicy
  cnn_model_type: dmcnn
  fc_features_dim: 128
  tau: 0.001

training_params:
  total_training_steps: 100_000
  batch_size: 128
  train_freq_type: step
  train_freq_num: 100

output_params:
  savedir: /scratch/str8775/conda_env/rl_project/models/
  savename: null
  logdir: /scratch/str8775/conda_env/rl_project/logs

callback_params:
  ckpt_freq: 1000
...