---
# general params
env_params:
  # high level params
  domain_name: hopper
  task_name: stand

  # image params
  height: 224
  width: 224

  # basic env params
  from_pixels: true
  visualize_reward: false

agent_params:
  # agent and extractor
  algo: PPO
  model_type: CnnPolicy
  cnn_model_type: resnet18
  fc_features_dim: 128

training_params:
  total_training_steps: 100_000
  learning_rate: 3e-4

output_params:
  savedir: /scratch/str8775/conda_env/rl_project/models/
  savename: null
  logdir: /scratch/str8775/conda_env/rl_project/logs

callback_params:
  ckpt_freq: 1000
...