---
# general params
env_params:
  # high level params
  domain_name: walker
  task_name: stand

  # image params
  height: 240
  width: 320

  # basic env params
  from_pixels: true
  visualize_reward: false

agent_params:
  # agent and extractor
  algo: PPO
  model_type: CnnPolicy
  cnn_model_type: dmcnn
  fc_features_dim: 128

training_params:
  resume_training: false
  load_model_ckpt_path: null
  is_transfer_learning: true

  total_training_steps: 3_000_000
  use_sde: true
  batch_size: 64
  train_freq_type: step
  train_freq_num: 100
  learning_rate: 0.0003

transfer_learning:
  original_task:
    domain_name: walker
    task_name: stand

  transfer_task:
    domain_name: walker
    task_name: walk


output_params:
  savedir: /scratch/str8775/conda_env/rl_project/models/transfer_learning/
  savename: null
  logdir: /scratch/str8775/conda_env/rl_project/logs/transfer_learning/

callback_params:
  ckpt_freq: 1000
...
