---
# general params
env_params:
  # high level params
  domain_name: walker
  task_name: walk

  # image params
  height: 240
  width: 320

  # basic env params
  from_pixels: true
  visualize_reward: false

agent_params:
  # agent and extractor
  algo: PPO
  model_type: CnnPolicy
  cnn_model_type: dmcnn
  fc_features_dim: 128
  tau: 0.001

training_params:
  resume_training: true
  load_model_ckpt_path: /scratch/str8775/conda_env/rl_project/logs/transfer_learning/PPO/dmcnn/walker/stand/1682639146/best_model-PPO-walker-stand-1682639146.zip
  is_transfer_learning: true

  total_training_steps: 3_000_000
  use_sde: true
  batch_size: 64
  train_freq_type: step
  train_freq_num: 500
  learning_rate: 0.0003

transfer_learning:
  original_task:
    domain_name: walker
    task_name: stand

  transfer_task:
    domain_name: walker
    task_name: walk

output_params:
  savedir: /scratch/str8775/conda_env/rl_project/models/
  savename: null
  logdir: /scratch/str8775/conda_env/rl_project/logs/

callback_params:
  ckpt_freq: 1000
...
